#!/bin/bash
#
# iOS SSL Pinning Bypass - macOS Packet Filter (pf) Setup
#
# This script configures macOS pf (packet filter) to redirect HTTP/HTTPS traffic
# from VPN clients to a local proxy for SSL pinning bypass
#
# Original Linux Version: https://github.com/SahilH4ck4you/iOS-SSL-pinning-bypass-without-jalibreak
# macOS Port: Ahmed Aldeab (@0xfa7b)
# Date: March 2026
#
# Dependencies:
# - macOS 10.15+ (pf is built into macOS)
# - Admin/sudo privileges for firewall configuration
# - OpenVPN server running with utun0 interface
# - Proxy tool (Burp Suite, mitmproxy) listening on port 8080
#
# Features:
# - HTTP/HTTPS traffic redirection to port 8080
# - NAT configuration for VPN subnet
# - Automatic pf.conf backup
# - Anchor rules for easy management
# - Support for utun0 VPN interface (macOS specific)
#
# Usage:
#   sudo bash pf-setup.sh <iOS_VPN_CLIENT_IP>
#
# Example:
#   sudo bash pf-setup.sh 10.8.0.2
#
# After setup:
#   - pf is enabled automatically
#   - Traffic from VPN clients is redirected to port 8080
#   - Configure your proxy tool to listen on port 8080
#
# Management Commands:
#   Disable pf: sudo pfctl -d
#   Enable pf:  sudo pfctl -e
#   Reload rules: sudo pfctl -f /etc/pf.conf
#   Check status: sudo pfctl -s info
#
# Configuration Files:
#   Main rules: /etc/pf.conf
#   Backup: /etc/pf.conf.backup.*
#   Anchor: /etc/pf.anchors/ssl-bypass
#
# Security Notes:
# - This script modifies system firewall configuration
# - Requires sudo privileges
# - Creates backup of existing pf.conf
# - pf rules are loaded and enabled automatically
#
# Compatible with:
#   - macOS Catalina (10.15)+
#   - Apple Silicon (M1/M2/M3) and Intel Macs
#   - OpenVPN with utun0 interface
#   - Any proxy tool listening on port 8080
#

# Check if IP address argument is provided
if [ $# -eq 0 ]; then
    echo "❌ Error: Please provide an IP address"
    echo "📖 Usage: $0 <IP_ADDRESS>"
    echo "💡 Example: $0 192.168.1.100"
    exit 1
fi

IP_ADDRESS="$1"

# Validate IP address format (basic validation)
if ! [[ $IP_ADDRESS =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "❌ Error: Invalid IP address format"
    echo "📍 Please use format: xxx.xxx.xxx.xxx"
    exit 1
fi

# Check if running on macOS
if [[ "$(uname)" != "Darwin" ]]; then
    echo "❌ This script is designed for macOS only."
    echo "🐧 For Linux, use iptables-setup.sh instead"
    exit 1
fi

# Check if running with sudo
if [[ $EUID -ne 0 ]]; then
   echo "❌ This script must be run with sudo"
   echo "🔓 Try: sudo bash $0 $IP_ADDRESS"
   exit 1
fi

echo "🔥 macOS Packet Filter (pf) Setup for SSL Pinning Bypass"
echo "🎯 Configuring rules for IP: $IP_ADDRESS"
echo ""

# Create pf configuration file
PF_CONF="/etc/pf.conf"
BACKUP_CONF="/etc/pf.conf.backup.$(date +%Y%m%d_%H%M%S)"

# Backup existing pf.conf if it exists
if [[ -f "$PF_CONF" ]]; then
    echo "💾 Backing up existing pf.conf to $BACKUP_CONF"
    cp "$PF_CONF" "$BACKUP_CONF"
fi

# Create new pf configuration
echo "📝 Creating pf configuration..."
cat > "$PF_CONF" << EOF
# macOS pf configuration for SSL pinning bypass
# Generated by pf-setup.sh

# Basic pf setup
set block-policy drop
set loginterface egress
set skip on lo0

# NAT setup for VPN traffic
nat on utun0 from $IP_ADDRESS/24 to any -> (utun0)

# Port redirection for HTTP/HTTPS to proxy (port 8080)
rdr on utun0 inet proto tcp from any to any port 80 -> 127.0.0.1 port 8080
rdr on utun0 inet proto tcp from any to any port 443 -> 127.0.0.1 port 8080

# Allow all traffic on loopback
pass quick on lo0 all

# Allow VPN traffic
pass quick on utun0 all

# Allow established connections
pass out all keep state

# Default allow rule
pass all
EOF

echo "✅ pf configuration created"

# Create anchor file for dynamic rules
ANCHOR_DIR="/etc/pf.anchors"
mkdir -p "$ANCHOR_DIR"

echo "🔗 Creating anchor file for dynamic rules..."
cat > "$ANCHOR_DIR/ssl-bypass" << EOF
# SSL bypass anchor rules
# This file can be reloaded without restarting pf
# Created by pf-setup.sh - macOS SSL Pinning Bypass

# Additional redirection rules can be added here
rdr on utun0 inet proto tcp from any to any port 80 -> 127.0.0.1 port 8080
rdr on utun0 inet proto tcp from any to any port 443 -> 127.0.0.1 port 8080
EOF

echo "✅ Anchor file created"

# Load pf configuration
echo "🔄 Loading pf configuration..."
pfctl -f "$PF_CONF"

if [[ $? -eq 0 ]]; then
    echo "✅ pf configuration loaded successfully"
else
    echo "❌ Failed to load pf configuration"
    echo "🔄 Attempting to restore backup..."
    if [[ -f "$BACKUP_CONF" ]]; then
        pfctl -f "$BACKUP_CONF"
    fi
    exit 1
fi

# Enable pf
echo "🚀 Enabling pf firewall..."
pfctl -e

if [[ $? -eq 0 ]]; then
    echo "✅ pf enabled successfully"
else
    echo "❌ Failed to enable pf"
    exit 1
fi

# Load anchor
echo "🔗 Loading SSL bypass anchor..."
pfctl -a ssl-bypass -f "$ANCHOR_DIR/ssl-bypass"

if [[ $? -eq 0 ]]; then
    echo "✅ Anchor loaded successfully"
else
    echo "⚠️  Failed to load anchor (may not be critical)"
fi

# Display current pf rules
echo ""
echo "📊 Current pf rules:"
pfctl -s rules

echo ""
echo "🌐 Current NAT rules:"
pfctl -s nat

echo ""
echo "🎉 Setup complete!"
echo ""
echo "📋 Management Commands:"
echo "   🔴 Disable pf: sudo pfctl -d"
echo "   🟢 Enable pf:  sudo pfctl -e"
echo "   🔄 Reload rules: sudo pfctl -f /etc/pf.conf"
echo "   📊 View status: sudo pfctl -s info"
echo ""
echo "📁 Configuration Files:"
echo "   📄 Main rules: $PF_CONF"
echo "   💾 Backup: $BACKUP_CONF"
echo "   🔗 Anchor: $ANCHOR_DIR/ssl-bypass"
echo ""
echo "⚠️  Important Notes:"
echo "   ✅ pf is now enabled and will start automatically on boot"
echo "   🎯 Make sure your proxy tool (Burp Suite, mitmproxy) is listening on port 8080"
echo "   🔌 Configure proxy to accept connections from the VPN interface (utun0)"
echo "   📱 Traffic from iOS VPN clients will be redirected to your proxy"
echo ""
echo "👤 macOS Port by: Ahmed Aldeab (@0xfa7b)"
echo "🌟 Original project: https://github.com/SahilH4ck4you/iOS-SSL-pinning-bypass-without-jalibreak"
